{
  "formatVersion": "1.1",
  "component": {
    "group": "com.thewebsnippet",
    "module": "manager",
    "version": "0.13.0-develop",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.thewebsnippet",
          "module": "data",
          "version": {
            "requires": "0.13.0-develop"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "manager-0.13.0-develop.aar",
          "url": "manager-0.13.0-develop.aar",
          "size": 183140,
          "sha512": "637c71f12b7222a23d5ccccf748812e58ee553337052f66ab23a5fb6a9759c3027bce1c2f074dc3f7319c89f9377f47f7243f0e8770278fecd227485d6563ae9",
          "sha256": "bc0dbf943f766bd06a5eb94feb89193471a44b4a6a5f25ed333f79c1f2f9a506",
          "sha1": "94fec6f9b55336e473b41a34768ad2a71ca4702c",
          "md5": "4f88652a376ef73b2538f029eda88f2f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.rickbusarow.dispatch",
          "module": "dispatch-core",
          "version": {
            "requires": "1.0.0-beta10"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.appmattus.certificatetransparency",
          "module": "certificatetransparency",
          "version": {
            "requires": "2.5.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "jakarta.inject",
          "module": "jakarta.inject-api",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.thewebsnippet",
          "module": "data",
          "version": {
            "requires": "0.13.0-develop"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "manager-0.13.0-develop.aar",
          "url": "manager-0.13.0-develop.aar",
          "size": 183140,
          "sha512": "637c71f12b7222a23d5ccccf748812e58ee553337052f66ab23a5fb6a9759c3027bce1c2f074dc3f7319c89f9377f47f7243f0e8770278fecd227485d6563ae9",
          "sha256": "bc0dbf943f766bd06a5eb94feb89193471a44b4a6a5f25ed333f79c1f2f9a506",
          "sha1": "94fec6f9b55336e473b41a34768ad2a71ca4702c",
          "md5": "4f88652a376ef73b2538f029eda88f2f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "manager-0.13.0-develop-sources.jar",
          "url": "manager-0.13.0-develop-sources.jar",
          "size": 158470,
          "sha512": "b9c9bda889219998ef361d0090f44959394686e115713a0aac69ff8e698cc7a7c855d8a585ad2439b1e76fc20918b0f80016e657bb8f27d17fe5013cfa288e67",
          "sha256": "a6726bbeaf4098ce7f09bac565be7fe4229027044829c07f84955dea65c1b6a8",
          "sha1": "1ca890049ea3e823d3a35223dd7ed9412a5ee53f",
          "md5": "2a347e554d01091f0b5aa701e4cac362"
        }
      ]
    }
  ]
}
