{
  "formatVersion": "1.1",
  "component": {
    "group": "com.thewebsnippet",
    "module": "data",
    "version": "0.13.0-develop",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "data-0.13.0-develop.aar",
          "url": "data-0.13.0-develop.aar",
          "size": 15496,
          "sha512": "54aa37fcf005dde504c64a9716a4a37a7b5841de3052f9c9354a3b9fdc61eaea56f769661c28f06101b30e05ddd9466eae216d09b0604d53eba1d2bc722f1153",
          "sha256": "da1a252041255c4a660242d0daf8f6ef555288fec364bee45c96c0f9b13d9e7c",
          "sha1": "43233a09412bb6dc9d7360893ce2513a9cd74b8b",
          "md5": "30e878d374b4037039f78538dadad21a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "data-0.13.0-develop.aar",
          "url": "data-0.13.0-develop.aar",
          "size": 15496,
          "sha512": "54aa37fcf005dde504c64a9716a4a37a7b5841de3052f9c9354a3b9fdc61eaea56f769661c28f06101b30e05ddd9466eae216d09b0604d53eba1d2bc722f1153",
          "sha256": "da1a252041255c4a660242d0daf8f6ef555288fec364bee45c96c0f9b13d9e7c",
          "sha1": "43233a09412bb6dc9d7360893ce2513a9cd74b8b",
          "md5": "30e878d374b4037039f78538dadad21a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "data-0.13.0-develop-sources.jar",
          "url": "data-0.13.0-develop-sources.jar",
          "size": 14215,
          "sha512": "d4c7f167a4b9d36106eedd1a2948205cc8d9011c23491c791885397fa684effeb8d2aa147514f88a8b1f4dbd3662926d8cca546633e59c536c5b888a3acf5090",
          "sha256": "4389d7bf764f0daa824f11f89063b914fb23a9e3e4ece73a9d9b468bf2dff74c",
          "sha1": "bfaa3c84d0dc9babae7c687e3d8e1c5d6cbb672f",
          "md5": "e603ed21c8e6775d88381bd654fef60c"
        }
      ]
    }
  ]
}
