[versions]
androidx-activity-compose = "1.9.3"
androidx-core-splashscreen = "1.0.1"
androidx-compose-runtime = "1.7.5"
androidx-lifecycle = "2.8.7"
androidx-test-orchestrator = "1.5.1"
androidx-test-espresso = "3.6.1"
androidx-test-runner = "1.6.2"
androidx-compose-material = "1.7.5"
androidx-compose-material3 = "1.3.1"
dagger = "2.52"
desugarJdkLibs = "2.1.3"
dispatch = "1.0.0-beta10"
kotlin = "2.0.21"
kotlin-immutableCollections = "0.3.7"
kotlinova = "3.3.0"
gradle = "8.7.2"
tws = "0.13.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose-material" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-runtime" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose-runtime" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "androidx-compose-runtime" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-compose-runtime" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-runtime" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose-runtime" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidx-compose-runtime" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidx-test-orchestrator" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
dagger-runtime = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLibs" }
dispatch = { module = "com.rickbusarow.dispatch:dispatch-core", version.ref = "dispatch" }
kotlin-immutableCollections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlin-immutableCollections" }
kotlinova-core = { module = "si.inova.kotlinova:core", version.ref = "kotlinova" }
tws-core = { group = "si.inova.tws", name = "core", version.ref = "tws" }
tws-manager = { group = "si.inova.tws", name = "manager", version.ref = "tws" }
tws-interstitial = { group = "si.inova.tws", name = "interstitial", version.ref = "tws" }

[plugins]
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
app = { id = "com.android.application", version.ref = "gradle" }
kotlin = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
