{
  "formatVersion": "1.1",
  "component": {
    "group": "com.thewebsnippet",
    "module": "core",
    "version": "0.13.0-develop",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.thewebsnippet",
          "module": "data",
          "version": {
            "requires": "0.13.0-develop"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.13.0-develop.aar",
          "url": "core-0.13.0-develop.aar",
          "size": 174030,
          "sha512": "4f7108db5696469e4983982f655061629d35a16861222cda842a043019bf83749a93b17f7766467e8032880945d514281c94660dff60030918cfea49611b925c",
          "sha256": "f71b352418b1230715c4d04a14a0327d28b91e9bc6f6ed863eb10bf4c738259b",
          "sha1": "38fba27b83be4600b2af81d90f5ca9715ebe3f34",
          "md5": "64542f807981014a2ffdf25895522939"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-collections-immutable",
          "version": {
            "requires": "0.3.7"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.35.1-alpha"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose-android",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "jakarta.inject",
          "module": "jakarta.inject-api",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.samskivert",
          "module": "jmustache",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "com.thewebsnippet",
          "module": "data",
          "version": {
            "requires": "0.13.0-develop"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.13.0-develop.aar",
          "url": "core-0.13.0-develop.aar",
          "size": 174030,
          "sha512": "4f7108db5696469e4983982f655061629d35a16861222cda842a043019bf83749a93b17f7766467e8032880945d514281c94660dff60030918cfea49611b925c",
          "sha256": "f71b352418b1230715c4d04a14a0327d28b91e9bc6f6ed863eb10bf4c738259b",
          "sha1": "38fba27b83be4600b2af81d90f5ca9715ebe3f34",
          "md5": "64542f807981014a2ffdf25895522939"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.13.0-develop-sources.jar",
          "url": "core-0.13.0-develop-sources.jar",
          "size": 162552,
          "sha512": "ee3f5c88b8262a594533dcbaad070e5a5d71427445f1bab7c57578e45e77298c6ba70888e809a145398f4a0ec1fd31e6d601ce0f5c4a57087661b0e8a63bc079",
          "sha256": "a098e1b201912c12888e2c59974752bb39e27c55fb4c1274daac71747a75b64b",
          "sha1": "56bffc7e22c29fe96c056d49208f071b3298ceab",
          "md5": "617798b8f40f3e92fe7b3119f0425e89"
        }
      ]
    }
  ]
}
