{
  "formatVersion": "1.1",
  "component": {
    "group": "com.thewebsnippet",
    "module": "service",
    "version": "0.13.0-develop",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "service-0.13.0-develop.jar",
          "url": "service-0.13.0-develop.jar",
          "size": 15920,
          "sha512": "cf389103b38922994a24aa70d762c1b84b8d02076010e36c4d859f0ccb67bb31653f049fdc3193fb0684e2aa3b097a6df1137b0f9d4d9fe65b73e496d5cf2552",
          "sha256": "79f7a6cebc77205b5d495339799069c48dc21edb7c48b32bec913da2b2c882cc",
          "sha1": "29b229ea1213d77f76bd944ee29cf21002a79f6c",
          "md5": "66b34f33b316677bdfa10c3e9d2ed8ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.4.0"
          }
        },
        {
          "group": "com.google.api-client",
          "module": "google-api-client",
          "version": {
            "requires": "2.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "service-0.13.0-develop.jar",
          "url": "service-0.13.0-develop.jar",
          "size": 15920,
          "sha512": "cf389103b38922994a24aa70d762c1b84b8d02076010e36c4d859f0ccb67bb31653f049fdc3193fb0684e2aa3b097a6df1137b0f9d4d9fe65b73e496d5cf2552",
          "sha256": "79f7a6cebc77205b5d495339799069c48dc21edb7c48b32bec913da2b2c882cc",
          "sha1": "29b229ea1213d77f76bd944ee29cf21002a79f6c",
          "md5": "66b34f33b316677bdfa10c3e9d2ed8ee"
        }
      ]
    }
  ]
}
