name: Generate Documentation

on:
  push:
    branches:
      - feat-update_docs

jobs:
  generate-documentation:
    name: Generate updated documentation
    runs-on: "ubuntu-latest"

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: feat-update_docs

      # Step 2: Set up Java environment (needed for Dokka)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # Step 3: Parse new SDK version
      - name: Parse SDK version
        id: parse_version
        run: |
          VERSION=$(cat version.txt)
          echo "SDK Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Step 4: Run the Dokka task
      - name: Generate documentation with Dokka
        run: ./gradlew dokkaHtmlMultiModule

      # Debug Step: List files in build directory after Dokka task
      - name: List files in build directory
        run: ls -R build

      # Step 5: Prepare the documentation for deployment
      - name: Prepare documentation for deployment
        run: |
          mkdir -p docs/$VERSION
          cp -r build/dokka/htmlMultiModule/* docs/$VERSION/
          mkdir -p docs/main
          cp -r build/dokka/htmlMultiModule/* docs/main/

      # Debug Step: List files in docs directory after copying
      - name: List files in docs directory
        run: ls -R docs

      # Step 6: Save generated documentation to a temporary location
      - name: Save generated documentation
        run: |
          mkdir -p /tmp/generated_docs
          cp -r docs/* /tmp/generated_docs/

      # Debug Step: List files in temporary location
      - name: List files in temporary location
        run: ls -R /tmp/generated_docs

      # Step 7: Checkout gh-pages branch
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      # Step 8: Copy generated docs from temporary location to gh-pages
      - name: Copy generated docs to gh-pages
        run: |
          [ -d $VERSION ] && rm -rf $VERSION
          [ -d main ] && rm -rf main
          
          cp -r /tmp/generated_docs/$VERSION ./
          cp -r /tmp/generated_docs/main ./
          
          ls -R

      # Step 9: Commit and push changes to gh-pages
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && echo "No changes to commit" || git commit -m "Update documentation for version $VERSION"
          git push origin gh-pages