name: Generate Documentation

on:
  workflow_run:
    workflows: ['publish']
    types: [completed]

jobs:
  generate-documentation:
    name: Generate updated documentation
    runs-on: "ubuntu-latest"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      # Step 2: Set up Java environment (needed for Dokka)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # Step 3: Parse new SDK version
      - name: Parse SDK version
        id: parse_version
        run: |
          VERSION=$(cat version.txt)
          echo "SDK Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Step 4: Update version in documentation
      - name: Replace version in index.md
        run: |
          sed -i "s/{{version}}/$VERSION/g" docs/index.md
          sed -i "s/{{version}}/$VERSION/g" view/Module.md
          sed -i "s/{{version}}/$VERSION/g" manager/Module.md

      # Step 5: Run the Dokka task
      - name: Generate documentation with Dokka
        run: ./gradlew dokkaHtmlMultiModule

      # Step 6: Prepare the documentation for deployment
      - name: Prepare documentation for deployment
        run: |
          mkdir -p docs/$VERSION
          cp -r build/dokka/htmlMultiModule/* docs/$VERSION/
          mkdir -p docs/docs
          cp -r build/dokka/htmlMultiModule/* docs/docs/

      # Step 7: Save generated documentation to a temporary location
      - name: Save generated documentation
        run: |
          mkdir -p /tmp/generated_docs
          cp -r docs/* /tmp/generated_docs/

      # Step 8: Checkout gh-pages branch
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      # Step 9: Copy generated docs from temporary location to gh-pages
      - name: Copy generated docs to gh-pages
        run: |
          [ -d $VERSION ] && rm -rf $VERSION
          [ -d docs ] && rm -rf docs
          
          cp -r /tmp/generated_docs/$VERSION ./
          cp -r /tmp/generated_docs/docs ./

      # Step 10: Commit and push changes to gh-pages
      - name: Commit and push changes
        run: |
          touch .nojekyll
          git config user.email "ci@inova.si"
          git config user.name "Build Bot"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "Update documentation for version $VERSION" --no-verify
            git push origin gh-pages
          else
            echo "No changes detected, skipping commit and push."
          fi
