name: "Pull Request"
run-name: "Pull Request"
on:
  pull_request:
    types: [ 'opened', 'reopened','synchronize', 'edited' ]
jobs:
  build-app:
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    runs-on: "ubuntu-latest"
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          cache: gradle
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - run: "v=$(cat version.txt);echo \"OLD_VERSION=$v\" > $GITHUB_ENV"
      - name: Check if there were any new fix or feature commits
        id: version-check
        uses: inovait/actions-common/bump-version-since-last-build@v10
        with:
          version: '${{ env.OLD_VERSION }}'

      - name: Generate Changelog
        id: changelog
        uses: inovait/actions-common/changelog-since-last-build@v10
        with:
          git_commit_url_prefix: 'https://github.com/inovait/tws-android-sdk/commit/'
      - run: "old_changelog=$(cat CHANGELOG.MD); echo \"# ${{ env.VERSION }}\n\n${{ steps.changelog.outputs.changelog }}\n\n$old_changelog\" > CHANGELOG.MD"

      - name: 'Add changelog and version'
        run: 'git add version.txt CHANGELOG.MD'
      - run: 'git config --global user.email "ci@inova.si"'
      - run: 'git config --global user.name "Build Bot"'
      - name: 'Commit changelog and version'
        run: 'git commit -m "chore: release ${{ env.VERSION }}"'
      - name: 'Push changelog and version'
        run: 'git push'

      - name: "Detekt"
        run: "./gradlew --continue :buildSrc:detekt detektRelease detektDebug detektDebugAndroidTest :service:detekt"

      - name: Compile library
        run: "./gradlew --parallel assemble"

      - name: "Compile Unit Tests"
        run: "./gradlew --parallel compileReleaseUnitTestSources compileDebugUnitTestSources assembleDebugAndroidTest"

      - name: "Run Unit Tests"
        run: "./gradlew --continue test service:test"
