name: "Pull Request"
run-name: "Pull Request"
on:
  pull_request:
    types: [ 'opened', 'reopened','synchronize', 'edited' ]
jobs:
  build-app:
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    runs-on: "ubuntu-latest"
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          cache: gradle
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: "Detekt"
        run: "./gradlew --continue :buildSrc:detekt detektRelease detektDebug detektDebugAndroidTest :service:detekt"

      - name: Compile library
        run: "./gradlew --parallel assemble"

      - name: "Compile Unit Tests"
        run: "./gradlew --parallel compileReleaseUnitTestSources compileDebugUnitTestSources assembleDebugAndroidTest"

      - name: "Run Unit Tests"
        run: "./gradlew --continue test service:test"
